name: 🌿 Green Garden Auto Commit

on:
  schedule:
    - cron: '*/10 * * * *'  
  workflow_dispatch:

permissions:
  contents: write

jobs:
  garden:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Water the plant (update existing file)
        run: |
          echo "🌱 Plant watered: $(date '+%Y-%m-%d %H:%M:%S')" >> text.txt

      - name: Commit and Push
        run: |
          git config --global user.name "buildwithzee"
          git config --global user.email "buildwithzee@gmail.com"
          git add text.txt
          git commit -m "🌿 Watered the garden at $(date '+%Y-%m-%d %H:%M:%S')"
